export enum ActionType {
  CART_ADD_ITEM = "CART_ADD_ITEM",
  CART_REMOVE_ITEM = "CART_REMOVE_ITEM",
  CART_SAVE_SHIPPING_ITEM = "CART_SAVE_SHIPPING_ITEM",
  CART_SAVE_PAYMENT_ITEM = "CART_SAVE_PAYMENT_ITEM",
  CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS",
}
